### ISSUE TITLE
Support for MITRA K551RGB-1

### ISSUE THREAD

**Issue by fellowabhi** [LeandroSQ/redragon-rgb-controller#1]
NAME : **MITRA**
MODEL : **K551RGB-1**

Test Status: Followed the instructions mentioned [here](https://github.com/LeandroSQ/redragon-rgb-controller#usage) and seems to not working for this model

**Comment by LeandroSQ** [comment]
I am sorry for not seeing this before, I did not receive notifications for your comment.

Not sure if you still want help, but just in case you do:

Unfortunately this was a reverse engineering project, and I only had the Kala keyboard so it is the only keyboard it supports. I am afraid the code as is will not be of much use for you. You can try to follow the steps I described on how to do the reverse engineering, but that would be on your own. You can find them on the README.md file.
